-- PARTE 1: Remove policies permissivas (tabelas A-M)
DROP POLICY IF EXISTS "service_role_all_benefit_partners" ON benefit_partners;
DROP POLICY IF EXISTS "tenant_isolation_insert_benefit_partners" ON benefit_partners;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON benefit_partners;
DROP POLICY IF EXISTS "tenant_isolation_select_benefit_partners" ON benefit_partners;
DROP POLICY IF EXISTS "tenant_isolation_update_benefit_partners" ON benefit_partners;
DROP POLICY IF EXISTS "benefits_partners_policy" ON benefits_partners;
DROP POLICY IF EXISTS "service_role_all_burial_records" ON burial_records;
DROP POLICY IF EXISTS "tenant_isolation_insert_burial_records" ON burial_records;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON burial_records;
DROP POLICY IF EXISTS "tenant_isolation_select_burial_records" ON burial_records;
DROP POLICY IF EXISTS "tenant_isolation_update_burial_records" ON burial_records;
DROP POLICY IF EXISTS "chapel_burials_policy" ON chapel_burials;
DROP POLICY IF EXISTS "service_role_all_collection_receipts" ON collection_receipts;
DROP POLICY IF EXISTS "tenant_isolation_insert_collection_receipts" ON collection_receipts;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON collection_receipts;
DROP POLICY IF EXISTS "tenant_isolation_select_collection_receipts" ON collection_receipts;
DROP POLICY IF EXISTS "service_role_all_collection_routes" ON collection_routes;
DROP POLICY IF EXISTS "tenant_isolation_insert_collection_routes" ON collection_routes;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON collection_routes;
DROP POLICY IF EXISTS "tenant_isolation_select_collection_routes" ON collection_routes;
DROP POLICY IF EXISTS "tenant_isolation_update_collection_routes" ON collection_routes;
DROP POLICY IF EXISTS "Permitir insercao publica" ON contracts;
DROP POLICY IF EXISTS "Permitir leitura contracts" ON contracts;
DROP POLICY IF EXISTS "Permitir leitura publica" ON contracts;
DROP POLICY IF EXISTS "auth_full_access_contracts" ON contracts;
DROP POLICY IF EXISTS "service_role_all_contracts" ON contracts;
DROP POLICY IF EXISTS "tenant_isolation_insert_contracts" ON contracts;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON contracts;
DROP POLICY IF EXISTS "tenant_isolation_select_contracts" ON contracts;
DROP POLICY IF EXISTS "tenant_isolation_update_contracts" ON contracts;
DROP POLICY IF EXISTS "Allow public all on dependents" ON dependents;
DROP POLICY IF EXISTS "auth_full_access_dependents" ON dependents;
DROP POLICY IF EXISTS "service_role_all_dependents" ON dependents;
DROP POLICY IF EXISTS "tenant_isolation_insert_dependents" ON dependents;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON dependents;
DROP POLICY IF EXISTS "tenant_isolation_select_dependents" ON dependents;
DROP POLICY IF EXISTS "tenant_isolation_update_dependents" ON dependents;
DROP POLICY IF EXISTS "service_role_all_dispatch_audit_logs" ON dispatch_audit_logs;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON dispatch_audit_logs;
DROP POLICY IF EXISTS "Allow all access to duty_services" ON duty_services;
DROP POLICY IF EXISTS "Allow public all on emergency_dispatches" ON emergency_dispatches;
DROP POLICY IF EXISTS "auth_full_access_emergency_dispatches" ON emergency_dispatches;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON emergency_dispatches;
DROP POLICY IF EXISTS "auth_full_access_financial_transactions" ON financial_transactions;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON financial_transactions;
DROP POLICY IF EXISTS "Allow public all on fleet_expenses" ON fleet_expenses;
DROP POLICY IF EXISTS "auth_full_access_fleet_expenses" ON fleet_expenses;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON fleet_expenses;
DROP POLICY IF EXISTS "Allow public all on fleet_vehicles" ON fleet_vehicles;
DROP POLICY IF EXISTS "auth_full_access_fleet_vehicles" ON fleet_vehicles;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON fleet_vehicles;
DROP POLICY IF EXISTS "inventory_policy" ON inventory;
DROP POLICY IF EXISTS "Allow public all on inventory_items" ON inventory_items;
DROP POLICY IF EXISTS "Permitir insercao publica" ON payments;
DROP POLICY IF EXISTS "Permitir leitura publica" ON payments;
DROP POLICY IF EXISTS "auth_full_access_payments" ON payments;
DROP POLICY IF EXISTS "service_role_all_payments" ON payments;
DROP POLICY IF EXISTS "tenant_isolation_insert_payments" ON payments;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON payments;
DROP POLICY IF EXISTS "tenant_isolation_select_payments" ON payments;
DROP POLICY IF EXISTS "tenant_isolation_update_payments" ON payments;
DROP POLICY IF EXISTS "auth_full_access_regulatory_reserves" ON regulatory_reserves;
DROP POLICY IF EXISTS "tenant_isolation_policy" ON regulatory_reserves;