SET local check_function_bodies = off;

CREATE SEQUENCE "public"."duty_services_id_seq" AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;

CREATE TABLE "public"."pedrofsneto33's Org" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "tenant_id"  uuid,
  CONSTRAINT "pedrofsneto33's Org_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."pedrofsneto33's Org"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."accounts_payable" (
  "id"          uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"   uuid                     NOT NULL,
  "description" character varying(255)   NOT NULL,
  "amount"      numeric(10,2)            NOT NULL,
  "due_date"    date                     NOT NULL,
  "status"      character varying(20)    NOT NULL DEFAULT 'pendente'::character varying,
  "created_at"  timestamp with time zone DEFAULT now(),
  CONSTRAINT "accounts_payable_amount_check" CHECK ((amount >= (0)::numeric)),
  CONSTRAINT "accounts_payable_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."accounts_payable"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."asaas_customers" (
  "id"                uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"         uuid                     NOT NULL,
  "contract_id"       uuid,
  "asaas_customer_id" character varying(100)   NOT NULL,
  "billing_type"      character varying(20),
  "created_at"        timestamp with time zone DEFAULT now(),
  CONSTRAINT "asaas_customers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."asaas_customers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."audit_logs" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"  uuid                     NOT NULL,
  "action"     character varying(100)   NOT NULL,
  "user_email" character varying(255),
  "details"    text,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "audit_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."audit_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."benefit_partners" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"            text                     NOT NULL DEFAULT 'matriz'::text,
  "name"                 text                     NOT NULL,
  "category"             text                     NOT NULL DEFAULT 'Clínica Médica'::text,
  "discount_description" text                     NOT NULL,
  "phone"                text,
  "address"              text,
  "city"                 text                     DEFAULT 'Teresina - PI'::text,
  "status"               text                     NOT NULL DEFAULT 'Ativo'::text,
  "created_at"           timestamp with time zone DEFAULT now(),
  CONSTRAINT "benefit_partners_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."benefit_partners"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."benefits_partners" (
  "id"                  uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"           uuid,
  "partner_name"        character varying(255)   NOT NULL,
  "category"            character varying(100)   NOT NULL DEFAULT 'Comércio Geral'::character varying,
  "discount_percentage" numeric(5,2)             DEFAULT 20.0,
  "contact_info"        text,
  "created_at"          timestamp with time zone DEFAULT now(),
  CONSTRAINT "benefits_partners_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."benefits_partners"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."burial_records" (
  "id"                       uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"                text                     NOT NULL DEFAULT 'matriz'::text,
  "dispatch_id"              uuid,
  "contract_id"              text,
  "deceased_name"            text                     NOT NULL,
  "room_id"                  uuid,
  "wake_start"               timestamp with time zone NOT NULL,
  "wake_end"                 timestamp with time zone NOT NULL,
  "cemetery_name"            text                     NOT NULL,
  "cemetery_plot"            text                     NOT NULL,
  "burial_type"              text                     NOT NULL DEFAULT 'Sepultamento Tradicional'::text,
  "concession_type"          text                     NOT NULL DEFAULT 'Perpétua'::text,
  "burial_date"              date                     NOT NULL,
  "exhumation_eligible_date" date,
  "status"                   text                     NOT NULL DEFAULT 'Agendado'::text,
  "observations"             text,
  "created_at"               timestamp with time zone DEFAULT now(),
  CONSTRAINT "burial_records_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."burial_records"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."chapel_bookings" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "chapel_name"    text                     NOT NULL,
  "deceased_name"  text                     NOT NULL,
  "family_contact" text,
  "start_time"     timestamp with time zone NOT NULL,
  "end_time"       timestamp with time zone NOT NULL,
  "status"         text                     DEFAULT 'agendado'::text,
  "created_at"     timestamp with time zone DEFAULT now(),
  "tenant_id"      uuid,
  CONSTRAINT "chapel_bookings_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."chapel_bookings"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."chapel_burials" (
  "id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"         uuid,
  "contract_id"       uuid,
  "deceased_name"     character varying(255)   NOT NULL,
  "burial_date"       timestamp with time zone NOT NULL DEFAULT now(),
  "cemetery_location" character varying(255),
  "status"            character varying(50)    NOT NULL DEFAULT 'Agendado'::character varying,
  "created_at"        timestamp with time zone DEFAULT now(),
  CONSTRAINT "chapel_burials_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."chapel_burials"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."collection_receipts" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"        text                     NOT NULL DEFAULT 'matriz'::text,
  "route_id"         uuid,
  "collector_name"   text                     NOT NULL,
  "contract_id"      text,
  "holder_name"      text                     NOT NULL,
  "amount_collected" numeric(10,2)            NOT NULL,
  "payment_method"   text                     NOT NULL DEFAULT 'Dinheiro'::text,
  "received_at"      timestamp with time zone DEFAULT now(),
  "status"           text                     NOT NULL DEFAULT 'Recebido'::text,
  "notes"            text,
  "created_at"       timestamp with time zone DEFAULT now(),
  CONSTRAINT "collection_receipts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."collection_receipts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."collection_routes" (
  "id"              uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"       text                     NOT NULL DEFAULT 'matriz'::text,
  "name"            text                     NOT NULL,
  "collector_name"  text                     NOT NULL,
  "collector_phone" text,
  "neighborhoods"   text,
  "status"          text                     NOT NULL DEFAULT 'Ativa'::text,
  "created_at"      timestamp with time zone DEFAULT now(),
  CONSTRAINT "collection_routes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."collection_routes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."collector_routes" (
  "id"             uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "collector_name" text                     NOT NULL,
  "zone"           text                     NOT NULL,
  "status"         text                     DEFAULT 'ativo'::text,
  "total_receipts" numeric(10,2)            DEFAULT 0.00,
  "created_at"     timestamp with time zone DEFAULT now(),
  "tenant_id"      uuid,
  CONSTRAINT "collector_routes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."collector_routes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."commissions" (
  "id"          uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"   uuid                     NOT NULL,
  "contract_id" uuid,
  "seller_name" character varying(150)   NOT NULL,
  "amount"      numeric(10,2)            NOT NULL,
  "status"      character varying(20)    NOT NULL DEFAULT 'pendente'::character varying,
  "created_at"  timestamp with time zone DEFAULT now(),
  CONSTRAINT "commissions_amount_check" CHECK ((amount >= (0)::numeric)),
  CONSTRAINT "commissions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."commissions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."contracts" (
  "id"          uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "holder_id"   uuid                     NOT NULL,
  "plan_id"     uuid                     NOT NULL,
  "status"      character varying(20)    NOT NULL DEFAULT 'active'::character varying,
  "start_date"  date                     NOT NULL DEFAULT CURRENT_DATE,
  "created_at"  timestamp with time zone DEFAULT now(),
  "tenant_id"   uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "seller_name" character varying(150),
  "seller_id"   uuid,
  CONSTRAINT "contracts_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."contracts"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."convalescence_items" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"  uuid                     NOT NULL DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "code"       text                     NOT NULL,
  "name"       text                     NOT NULL,
  "category"   text                     NOT NULL DEFAULT 'Cadeira de Rodas'::text,
  "status"     text                     NOT NULL DEFAULT 'Disponível'::text,
  "condition"  text                     NOT NULL DEFAULT 'Novo'::text,
  "notes"      text,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "convalescence_items_code_key" UNIQUE (code),
  CONSTRAINT "convalescence_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."convalescence_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."convalescence_loans" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"            uuid                     NOT NULL,
  "item_id"              uuid,
  "contract_id"          text,
  "holder_name"          text                     NOT NULL,
  "holder_cpf"           text,
  "holder_phone"         text,
  "beneficiary_name"     text,
  "loan_date"            date                     NOT NULL DEFAULT CURRENT_DATE,
  "expected_return_date" date                     NOT NULL,
  "actual_return_date"   date,
  "deposit_amount"       numeric(10,2)            DEFAULT 0.00,
  "cleaning_fee"         numeric(10,2)            DEFAULT 0.00,
  "status"               text                     NOT NULL DEFAULT 'Ativo'::text,
  "return_condition"     text,
  "observations"         text,
  "created_at"           timestamp with time zone DEFAULT now(),
  "updated_at"           timestamp with time zone DEFAULT now(),
  CONSTRAINT "convalescence_loans_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."convalescence_loans"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."dependents" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "holder_id"  uuid                     NOT NULL,
  "full_name"  character varying(150)   NOT NULL,
  "cpf"        character varying(14),
  "relation"   character varying(50)    NOT NULL,
  "birth_date" date,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id"  uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "dependents_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."dependents"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."dispatch_audit_logs" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"     uuid                     NOT NULL,
  "dispatch_id"   text                     NOT NULL,
  "action"        text                     NOT NULL,
  "actor_name"    text                     NOT NULL,
  "actor_role"    text                     NOT NULL DEFAULT 'atendente'::text,
  "vehicle_plate" text,
  "driver_name"   text,
  "details"       jsonb                    DEFAULT '{}'::jsonb,
  "created_at"    timestamp with time zone DEFAULT now(),
  CONSTRAINT "dispatch_audit_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."dispatch_audit_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."dispatches" (
  "id"                uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"         uuid                     NOT NULL,
  "vehicle_id"        uuid,
  "vehicle_plate"     character varying(15),
  "driver_agent"      character varying(150),
  "status"            character varying(30)    NOT NULL DEFAULT 'Em andamento'::character varying,
  "odometer_start"    numeric(10,1),
  "odometer_end"      numeric(10,1),
  "km_traveled"       numeric(10,1),
  "fuel_liters_added" numeric(10,2)            DEFAULT 0,
  "fuel_cost"         numeric(10,2)            DEFAULT 0,
  "closure_notes"     text,
  "closed_at"         timestamp with time zone,
  "created_at"        timestamp with time zone DEFAULT now(),
  CONSTRAINT "dispatches_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."dispatches"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."duty_services" (
  "id"             bigint                   NOT NULL DEFAULT nextval('public.duty_services_id_seq'::regclass),
  "contract_id"    bigint,
  "deceased_name"  text                     NOT NULL,
  "holder_name"    text,
  "death_location" text,
  "casket_model"   text,
  "status"         text                     DEFAULT 'em_andamento'::text,
  "notes"          text,
  "created_at"     timestamp with time zone DEFAULT now(),
  "updated_at"     timestamp with time zone DEFAULT now(),
  "tenant_id"      uuid,
  CONSTRAINT "duty_services_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."duty_services"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."emergency_dispatches" (
  "id"                   uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "protocol"             character varying(50)    NOT NULL,
  "deceased_name"        character varying(255)   NOT NULL,
  "holder_name"          character varying(255),
  "plan_name"            character varying(100),
  "death_location"       character varying(255),
  "address"              text,
  "urn_model"            character varying(150),
  "vehicle_id"           uuid,
  "vehicle_desc"         character varying(150),
  "driver_agent"         character varying(150),
  "family_contact_name"  character varying(150),
  "family_contact_phone" character varying(50),
  "observations"         text,
  "status"               character varying(30)    DEFAULT 'em_andamento'::character varying,
  "created_at"           timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "completed_at"         timestamp with time zone,
  "tenant_id"            uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "location"             text,
  "family_contact"       text,
  "caller_phone"         text,
  "source"               character varying(20)    NOT NULL DEFAULT 'telefone'::character varying,
  CONSTRAINT "emergency_dispatches_pkey" PRIMARY KEY (id),
  CONSTRAINT "emergency_dispatches_protocol_key" UNIQUE (protocol)
);

ALTER TABLE "public"."emergency_dispatches"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."financial_transactions" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "contract_id"      uuid,
  "amount"           numeric(10,2)            NOT NULL,
  "type"             text                     NOT NULL,
  "category"         text,
  "gateway_txid"     text,
  "description"      text,
  "created_at"       timestamp with time zone DEFAULT now(),
  "tenant_id"        uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "payment_id"       uuid,
  "transaction_date" timestamp with time zone DEFAULT now(),
  "service_order_id" uuid,
  CONSTRAINT "financial_transactions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."financial_transactions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."fiscal_invoices" (
  "id"                        uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"                 uuid                     NOT NULL,
  "service_order_id"          uuid,
  "provider"                  text,
  "provider_invoice_id"       text,
  "provider_environment"      text                     DEFAULT 'sandbox'::text,
  "nfse_number"               text,
  "nfse_verification_code"    text,
  "nfse_status"               text                     NOT NULL DEFAULT 'pending'::text,
  "taker_document_type"       text,
  "taker_document"            text,
  "taker_name"                text                     NOT NULL,
  "taker_email"               text,
  "taker_phone"               text,
  "taker_zip_code"            text,
  "taker_address"             text,
  "taker_number"              text,
  "taker_complement"          text,
  "taker_neighborhood"        text,
  "taker_city"                text,
  "taker_state"               text,
  "service_code"              text,
  "service_description"       text                     NOT NULL,
  "service_amount"            numeric(12,2)            NOT NULL,
  "deduction_amount"          numeric(12,2)            DEFAULT 0,
  "tax_rate"                  numeric(5,2),
  "iss_amount"                numeric(12,2),
  "taxable_amount"            numeric(12,2),
  "cst"                       text,
  "c_class_trib"              text,
  "ind_natureza_op"           text,
  "v_bc_ibs_cbs"              numeric(12,2),
  "p_ibs_cbs"                 numeric(5,2),
  "v_ibs"                     numeric(12,2),
  "v_cbs"                     numeric(12,2),
  "provider_request_payload"  jsonb,
  "provider_response_payload" jsonb,
  "provider_error_message"    text,
  "pdf_url"                   text,
  "xml_url"                   text,
  "cancelled_at"              timestamp with time zone,
  "cancelled_by_user_id"      uuid,
  "cancellation_reason"       text,
  "cancellation_nfse_number"  text,
  "created_by_user_id"        uuid,
  "created_at"                timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"                timestamp with time zone,
  "issued_at"                 timestamp with time zone,
  CONSTRAINT "fiscal_invoices_nfse_status_check"
    CHECK ((nfse_status = ANY (ARRAY['pending'::text, 'processing'::text, 'authorized'::text, 'rejected'::text, 'cancelled'::text, 'error'::text]))),
  CONSTRAINT "fiscal_invoices_pkey" PRIMARY KEY (id),
  CONSTRAINT "fiscal_invoices_provider_environment_check" CHECK ((provider_environment = ANY (ARRAY['sandbox'::text, 'production'::text]))),
  CONSTRAINT "fiscal_invoices_taker_document_type_check" CHECK ((taker_document_type = ANY (ARRAY['cpf'::text, 'cnpj'::text])))
);

ALTER TABLE "public"."fiscal_invoices"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."fleet_expenses" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "vehicle_id"    uuid,
  "expense_type"  character varying(50)    NOT NULL,
  "amount"        numeric(10,2)            NOT NULL,
  "current_km"    integer,
  "liters"        numeric(6,2),
  "establishment" character varying(150),
  "notes"         text,
  "expense_date"  date                     NOT NULL DEFAULT CURRENT_DATE,
  "created_at"    timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "tenant_id"     uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "fleet_expenses_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."fleet_expenses"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."fleet_vehicles" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "model"        character varying(100)   NOT NULL,
  "plate"        character varying(20)    NOT NULL,
  "vehicle_type" character varying(50)    DEFAULT 'Remoção'::character varying,
  "current_km"   integer                  DEFAULT 0,
  "status"       character varying(30)    DEFAULT 'disponivel'::character varying,
  "created_at"   timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "tenant_id"    uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "fleet_vehicles_pkey" PRIMARY KEY (id),
  CONSTRAINT "fleet_vehicles_plate_key" UNIQUE (plate)
);

ALTER TABLE "public"."fleet_vehicles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."holders" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "full_name"  character varying(150)   NOT NULL,
  "cpf"        character varying(14)    NOT NULL,
  "phone"      character varying(20)    NOT NULL,
  "email"      character varying(255),
  "address"    text,
  "created_at" timestamp with time zone DEFAULT now(),
  "tenant_id"  uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "status"     character varying(10)    NOT NULL DEFAULT 'ativo'::character varying,
  CONSTRAINT "holders_cpf_key" UNIQUE (cpf),
  CONSTRAINT "holders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."holders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."inventory_items" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"         character varying(255)   NOT NULL,
  "category"     character varying(100)   DEFAULT 'Urna'::character varying,
  "quantity"     integer                  NOT NULL DEFAULT 0,
  "min_quantity" integer                  NOT NULL DEFAULT 3,
  "updated_at"   timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "tenant_id"    uuid,
  CONSTRAINT "inventory_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."inventory_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."inventory" (
  "id"             uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "item_name"      character varying(150)   NOT NULL,
  "category"       character varying(50)    NOT NULL,
  "stock_quantity" integer                  NOT NULL DEFAULT 0,
  "min_threshold"  integer                  NOT NULL DEFAULT 5,
  "created_at"     timestamp with time zone DEFAULT now(),
  "tenant_id"      uuid,
  CONSTRAINT "inventory_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."inventory"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."leads" (
  "id"                  uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "name"                character varying(150)   NOT NULL,
  "company"             character varying(150),
  "city"                character varying(100),
  "uf"                  character varying(2),
  "phone"               character varying(25),
  "email"               character varying(150),
  "source"              character varying(30)    NOT NULL DEFAULT 'manual'::character varying,
  "stage"               character varying(30)    NOT NULL DEFAULT 'novo'::character varying,
  "estimated_monthly"   numeric(10,2)            NOT NULL DEFAULT 0,
  "next_follow_up"      date,
  "notes"               text,
  "lost_reason"         text,
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "converted_at"        timestamp with time zone,
  "converted_tenant_id" uuid,
  CONSTRAINT "leads_estimated_monthly_check" CHECK ((estimated_monthly >= (0)::numeric)),
  CONSTRAINT "leads_pkey" PRIMARY KEY (id),
  CONSTRAINT "leads_source_check"
    CHECK (((source)::text = ANY ((ARRAY['manual'::character varying, 'landing'::character varying, 'indicacao'::character varying, 'outbound'::character varying])::text[]))),
  CONSTRAINT "leads_stage_check"
    CHECK
    (((stage)::text = ANY ((ARRAY['novo'::character varying, 'contato'::character varying, 'demo'::character varying, 'proposta'::character varying, 'ganho'::character varying,
    'perdido'::character varying])::text[])))
);

ALTER TABLE "public"."leads"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."payment_carnets" (
  "id"                 uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"          uuid                     NOT NULL,
  "contract_id"        uuid                     NOT NULL,
  "installment_number" integer                  NOT NULL,
  "total_installments" integer                  NOT NULL,
  "due_date"           date                     NOT NULL,
  "amount"             numeric(10,2)            NOT NULL,
  "status"             character varying(20)    NOT NULL DEFAULT 'pendente'::character varying,
  "created_at"         timestamp with time zone DEFAULT now(),
  "holder_name"        character varying(255),
  "holder_cpf"         character varying(14),
  "asaas_payment_id"   character varying(100),
  CONSTRAINT "payment_carnets_amount_check" CHECK ((amount >= (0)::numeric)),
  CONSTRAINT "payment_carnets_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."payment_carnets"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."payments" (
  "id"               uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "contract_id"      uuid                     NOT NULL,
  "amount"           numeric(10,2)            NOT NULL,
  "due_date"         date                     NOT NULL,
  "paid_at"          timestamp with time zone,
  "status"           character varying(20)    NOT NULL DEFAULT 'pending'::character varying,
  "payment_method"   character varying(20)    DEFAULT 'pix'::character varying,
  "pix_code"         text,
  "pix_qr_code_url"  text,
  "created_at"       timestamp with time zone DEFAULT now(),
  "tenant_id"        uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "asaas_payment_id" character varying(100),
  CONSTRAINT "payments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."payments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."plans_orphans_backup" (
  "id"           uuid                     NOT NULL,
  "data"         jsonb                    NOT NULL,
  "backed_up_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "plans_orphans_backup_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."plans_orphans_backup"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."plans" (
  "id"                        uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "name"                      character varying(100)   NOT NULL,
  "monthly_fee"               numeric(10,2)            NOT NULL,
  "max_dependents"            integer                  NOT NULL DEFAULT 4,
  "description"               text,
  "created_at"                timestamp with time zone DEFAULT now(),
  "tenant_id"                 uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  "commission_rate_initial"   numeric(5,2)             NOT NULL DEFAULT 0,
  "commission_rate_recurring" numeric(5,2)             NOT NULL DEFAULT 0,
  CONSTRAINT "plans_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."plans"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."regulatory_reserves" (
  "id"                       uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"                uuid,
  "reference_month"          date                     NOT NULL,
  "gross_revenue"            numeric(12,2)            NOT NULL DEFAULT 0.00,
  "net_revenue"              numeric(12,2)            NOT NULL DEFAULT 0.00,
  "solvency_reserve_target"  numeric(12,2)            NOT NULL DEFAULT 0.00,
  "technical_reserve_target" numeric(12,2)            NOT NULL DEFAULT 0.00,
  "applied_amount"           numeric(12,2)            DEFAULT 0.00,
  "status"                   text                     DEFAULT 'calculado'::text,
  "created_at"               timestamp with time zone DEFAULT now(),
  CONSTRAINT "regulatory_reserves_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."regulatory_reserves"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sales_commissions" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "seller_name" text                     NOT NULL,
  "contract_id" uuid,
  "amount"      numeric(10,2)            NOT NULL,
  "status"      text                     DEFAULT 'pending'::text,
  "created_at"  timestamp with time zone DEFAULT now(),
  "tenant_id"   uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "sales_commissions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sales_commissions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sellers" (
  "id"                 uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"          uuid                     NOT NULL,
  "name"               character varying(150)   NOT NULL,
  "phone"              character varying(20),
  "whatsapp"           character varying(20),
  "commission_percent" numeric(5,2)             NOT NULL DEFAULT 0,
  "active"             boolean                  NOT NULL DEFAULT true,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"         timestamp with time zone,
  CONSTRAINT "sellers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sellers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."service_order_items" (
  "id"               uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"        uuid                     NOT NULL,
  "service_order_id" uuid,
  "inventory_id"     uuid,
  "quantity"         integer                  DEFAULT 1,
  "unit_price"       numeric(10,2)            DEFAULT 0,
  "created_at"       timestamp with time zone DEFAULT now(),
  CONSTRAINT "service_order_items_pkey" PRIMARY KEY (id),
  CONSTRAINT "service_order_items_quantity_check" CHECK ((quantity > 0))
);

ALTER TABLE "public"."service_order_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."service_orders" (
  "id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"         uuid                     NOT NULL,
  "contract_id"       uuid,
  "burial_id"         uuid,
  "vehicle_id"        uuid,
  "deceased_name"     text                     NOT NULL,
  "deceased_type"     text                     NOT NULL,
  "deceased_id"       uuid                     NOT NULL,
  "status"            text                     DEFAULT 'pending'::text,
  "burial_date"       timestamp with time zone,
  "cemetery_location" text,
  "notes"             text,
  "total_amount"      numeric(10,2)            DEFAULT 0,
  "created_at"        timestamp with time zone DEFAULT now(),
  "nfse_id"           uuid,
  "nfse_status"       text,
  "nfse_required"     boolean                  NOT NULL DEFAULT true,
  CONSTRAINT "service_orders_deceased_type_check" CHECK ((deceased_type = ANY (ARRAY['holder'::text, 'dependent'::text, 'free'::text]))),
  CONSTRAINT "service_orders_nfse_status_check"
    CHECK ((nfse_status = ANY (ARRAY['pending'::text, 'processing'::text, 'authorized'::text, 'rejected'::text, 'cancelled'::text, 'error'::text, 'not_applicable'::text]))),
  CONSTRAINT "service_orders_pkey" PRIMARY KEY (id),
  CONSTRAINT "service_orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])))
);

ALTER TABLE "public"."service_orders"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_items" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"         text                     NOT NULL,
  "category"     text                     NOT NULL,
  "quantity"     integer                  NOT NULL DEFAULT 0,
  "min_quantity" integer                  NOT NULL DEFAULT 1,
  "unit_cost"    numeric(10,2)            DEFAULT 0.00,
  "created_at"   timestamp with time zone DEFAULT now(),
  "tenant_id"    uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "stock_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."stock_movements" (
  "id"            uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "stock_item_id" uuid,
  "type"          text                     NOT NULL,
  "quantity"      integer                  NOT NULL,
  "reason"        text,
  "created_at"    timestamp with time zone DEFAULT now(),
  "tenant_id"     uuid                     DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "stock_movements_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."stock_movements"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tenant_whatsapp_numbers" (
  "id"                 uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"          uuid                     NOT NULL,
  "whatsapp_number"    character varying(20)    NOT NULL,
  "evolution_instance" character varying(100)   NOT NULL,
  "active"             boolean                  NOT NULL DEFAULT true,
  "created_at"         timestamp with time zone DEFAULT now(),
  CONSTRAINT "tenant_whatsapp_numbers_pkey" PRIMARY KEY (id),
  CONSTRAINT "tenant_whatsapp_numbers_whatsapp_number_key" UNIQUE (whatsapp_number)
);

ALTER TABLE "public"."tenant_whatsapp_numbers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."tenants" (
  "id"                                 uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "name"                               text                     NOT NULL,
  "trade_name"                         text,
  "cnpj"                               text                     NOT NULL,
  "phone_emergency"                    text,
  "primary_color"                      text                     DEFAULT '#10b981'::text,
  "logo_url"                           text,
  "municipal_license_number"           text,
  "issuance_city"                      text,
  "technical_manager"                  text,
  "asaas_api_key"                      text,
  "asaas_webhook_token"                text,
  "pix_key"                            text,
  "status"                             text                     DEFAULT 'active'::text,
  "created_at"                         timestamp with time zone DEFAULT now(),
  "asaas_wallet_id"                    text,
  "asaas_environment"                  character varying(20)    DEFAULT 'production'::character varying,
  "tenant_id"                          uuid,
  "commercial_plan"                    character varying(20)    DEFAULT 'essencial'::character varying,
  "fiscal_provider"                    text,
  "fiscal_environment"                 text                     DEFAULT 'sandbox'::text,
  "fiscal_api_key"                     text,
  "fiscal_company_document"            text,
  "fiscal_company_name"                text,
  "fiscal_company_zip"                 text,
  "fiscal_company_address"             text,
  "fiscal_company_number"              text,
  "fiscal_company_neighborhood"        text,
  "fiscal_company_city"                text,
  "fiscal_company_state"               text,
  "fiscal_company_phone"               text,
  "fiscal_company_email"               text,
  "fiscal_company_ibge_code"           text,
  "fiscal_company_tax_regime"          text,
  "fiscal_cnae"                        text,
  "fiscal_default_service_code"        text,
  "fiscal_default_service_description" text,
  "fiscal_default_iss_rate"            numeric(5,2)             DEFAULT 5.00,
  "fiscal_auto_emit"                   boolean                  NOT NULL DEFAULT false,
  "fiscal_last_test_at"                timestamp with time zone,
  "fiscal_last_test_status"            text,
  CONSTRAINT "tenants_cnpj_key" UNIQUE (cnpj),
  CONSTRAINT "tenants_commercial_plan_check"
    CHECK (((commercial_plan)::text = ANY ((ARRAY['essencial'::character varying, 'profissional'::character varying, 'enterprise'::character varying])::text[]))),
  CONSTRAINT "tenants_fiscal_company_tax_regime_check"
    CHECK ((fiscal_company_tax_regime = ANY (ARRAY['simples_nacional'::text, 'lucro_presumido'::text, 'lucro_real'::text, 'mei'::text]))),
  CONSTRAINT "tenants_fiscal_environment_check" CHECK ((fiscal_environment = ANY (ARRAY['sandbox'::text, 'production'::text]))),
  CONSTRAINT "tenants_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."tenants"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."thanatopraxy_records" (
  "id"                          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"                   uuid                     NOT NULL,
  "dispatch_id"                 uuid,
  "contract_id"                 text,
  "deceased_name"               text                     NOT NULL,
  "death_cause"                 text,
  "thanatopractor_name"         text                     NOT NULL,
  "thanatopractor_register"     text,
  "method"                      text                     NOT NULL DEFAULT 'Tanatopraxia Nível II'::text,
  "procedure_date"              timestamp with time zone DEFAULT now(),
  "arterial_fluid_ml"           numeric(10,2)            DEFAULT 0,
  "cavity_fluid_ml"             numeric(10,2)            DEFAULT 0,
  "other_supplies"              text,
  "body_condition"              text                     DEFAULT 'Normal'::text,
  "preservation_validity_hours" integer                  DEFAULT 48,
  "observations"                text,
  "created_at"                  timestamp with time zone DEFAULT now(),
  CONSTRAINT "thanatopraxy_records_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."thanatopraxy_records"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_roles" (
  "id"         uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "user_id"    uuid                     NOT NULL,
  "tenant_id"  uuid,
  "role"       character varying(50)    NOT NULL DEFAULT 'attendant'::character varying,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "user_roles_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_roles_user_id_tenant_id_key" UNIQUE (user_id, tenant_id)
);

ALTER TABLE "public"."user_roles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."vehicles" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "created_at"  timestamp with time zone DEFAULT now(),
  "plate"       text                     NOT NULL,
  "model"       text                     NOT NULL,
  "brand"       text,
  "year"        integer,
  "status"      text                     DEFAULT 'available'::text,
  "driver_name" text,
  "fuel_level"  text,
  "notes"       text,
  "tenant_id"   uuid                     NOT NULL DEFAULT 'a0000000-0000-0000-0000-000000000001'::uuid,
  CONSTRAINT "vehicles_pkey" PRIMARY KEY (id),
  CONSTRAINT "vehicles_plate_key" UNIQUE (plate)
);

ALTER TABLE "public"."vehicles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."wake_rooms" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"  text                     NOT NULL DEFAULT 'matriz'::text,
  "name"       text                     NOT NULL,
  "capacity"   integer                  DEFAULT 50,
  "status"     text                     NOT NULL DEFAULT 'Disponível'::text,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "wake_rooms_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."wake_rooms"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."webhook_events" (
  "id"               uuid                     NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "tenant_id"        uuid,
  "provider"         character varying(30)    NOT NULL DEFAULT 'asaas'::character varying,
  "event"            character varying(60),
  "asaas_payment_id" character varying(100),
  "processed"        boolean                  NOT NULL DEFAULT false,
  "skipped_reason"   text,
  "payload"          jsonb,
  "received_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "processed_at"     timestamp with time zone,
  "retry_count"      integer                  NOT NULL DEFAULT 0,
  "last_retried_at"  timestamp with time zone,
  "retry_error"      text,
  CONSTRAINT "webhook_events_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."webhook_events"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."webhook_logs" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "gateway"    character varying(50)    DEFAULT 'PIX_GATEWAY'::character varying,
  "payload"    jsonb                    NOT NULL,
  "status"     character varying(20)    DEFAULT 'processed'::character varying,
  "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  "tenant_id"  uuid,
  CONSTRAINT "webhook_logs_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."webhook_logs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."whatsapp_agent_sessions" (
  "id"         uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "tenant_id"  uuid                     NOT NULL,
  "phone"      character varying(20)    NOT NULL,
  "step"       character varying(40)    NOT NULL DEFAULT 'init'::character varying,
  "data"       jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "whatsapp_agent_sessions_pkey" PRIMARY KEY (id),
  CONSTRAINT "whatsapp_agent_sessions_tenant_id_phone_key" UNIQUE (tenant_id, phone)
);

ALTER TABLE "public"."whatsapp_agent_sessions"
  ENABLE ROW LEVEL SECURITY;

ALTER SEQUENCE "public"."duty_services_id_seq" OWNED BY "public"."duty_services"."id";

CREATE OR REPLACE FUNCTION public.current_tenant_id()
  RETURNS text
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  AS $function$
BEGIN
  RETURN COALESCE(
    current_setting('request.jwt.claims', true)::jsonb -> 'app_metadata' ->> 'tenant_id',
    current_setting('request.jwt.claims', true)::jsonb -> 'user_metadata' ->> 'tenant_id',
    'matriz'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.decrement_stock (
  item_id uuid,
  qty     integer
)
  RETURNS void
  LANGUAGE plpgsql
  AS $function$
BEGIN
  UPDATE inventory
  SET stock_quantity = stock_quantity - qty
  WHERE id = item_id AND stock_quantity >= qty;
END;
$function$;

CREATE OR REPLACE FUNCTION public.decrement_stock (
  p_item_id   uuid,
  p_tenant_id uuid,
  qty         integer
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
BEGIN
  UPDATE public.inventory
  SET stock_quantity = stock_quantity - qty
  WHERE id = p_item_id AND tenant_id = p_tenant_id AND stock_quantity >= qty;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_current_tenant_id()
  RETURNS text
  LANGUAGE sql
  STABLE
  AS $function$
  select nullif(current_setting('request.jwt.claims', true)::json->>'tenant_id', '')::text;
$function$;

CREATE OR REPLACE FUNCTION public.get_user_tenant_id()
  RETURNS uuid
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  AS $function$
    SELECT tenant_id FROM public.user_roles
    WHERE user_id = auth.uid()
    LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.increment_stock (
  p_item_id   uuid,
  p_tenant_id uuid,
  qty         integer
)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$
BEGIN
  UPDATE public.inventory
  SET stock_quantity = stock_quantity + qty
  WHERE id = p_item_id AND tenant_id = p_tenant_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_superadmin()
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.user_roles
        WHERE user_id = auth.uid() AND role = 'superadmin'
    );
$function$;

ALTER TABLE "public"."collection_receipts"
  ADD CONSTRAINT "collection_receipts_route_id_fkey" FOREIGN KEY (route_id) REFERENCES public.collection_routes(id) ON DELETE SET NULL;

ALTER TABLE "public"."asaas_customers"
  ADD CONSTRAINT "asaas_customers_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE SET NULL;

ALTER TABLE "public"."chapel_burials"
  ADD CONSTRAINT "chapel_burials_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE SET NULL;

ALTER TABLE "public"."commissions"
  ADD CONSTRAINT "commissions_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE SET NULL;

ALTER TABLE "public"."convalescence_loans"
  ADD CONSTRAINT "convalescence_loans_item_id_fkey" FOREIGN KEY (item_id) REFERENCES public.convalescence_items(id) ON DELETE CASCADE;

ALTER TABLE "public"."financial_transactions"
  ADD CONSTRAINT "financial_transactions_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE SET NULL;

ALTER TABLE "public"."emergency_dispatches"
  ADD CONSTRAINT "emergency_dispatches_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES public.fleet_vehicles(id) ON DELETE SET NULL;

ALTER TABLE "public"."fleet_expenses"
  ADD CONSTRAINT "fleet_expenses_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES public.fleet_vehicles(id) ON DELETE CASCADE;

ALTER TABLE "public"."contracts"
  ADD CONSTRAINT "contracts_holder_id_fkey" FOREIGN KEY (holder_id) REFERENCES public.holders(id) ON DELETE CASCADE;

ALTER TABLE "public"."dependents"
  ADD CONSTRAINT "dependents_holder_id_fkey" FOREIGN KEY (holder_id) REFERENCES public.holders(id) ON DELETE CASCADE;

ALTER TABLE "public"."payment_carnets"
  ADD CONSTRAINT "payment_carnets_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE;

ALTER TABLE "public"."payments"
  ADD CONSTRAINT "payments_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE;

ALTER TABLE "public"."contracts"
  ADD CONSTRAINT "contracts_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES public.plans(id);

ALTER TABLE "public"."sales_commissions"
  ADD CONSTRAINT "sales_commissions_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE;

ALTER TABLE "public"."contracts"
  ADD CONSTRAINT "contracts_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES public.sellers(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_order_items"
  ADD CONSTRAINT "service_order_items_inventory_id_fkey" FOREIGN KEY (inventory_id) REFERENCES public.inventory(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_orders"
  ADD CONSTRAINT "service_orders_burial_id_fkey" FOREIGN KEY (burial_id) REFERENCES public.chapel_burials(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_orders"
  ADD CONSTRAINT "service_orders_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_orders"
  ADD CONSTRAINT "service_orders_nfse_id_fkey" FOREIGN KEY (nfse_id) REFERENCES public.fiscal_invoices(id) ON DELETE SET NULL;

ALTER TABLE "public"."financial_transactions"
  ADD CONSTRAINT "financial_transactions_service_order_id_fkey" FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id) ON DELETE SET NULL;

ALTER TABLE "public"."fiscal_invoices"
  ADD CONSTRAINT "fiscal_invoices_service_order_id_fkey" FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_order_items"
  ADD CONSTRAINT "service_order_items_service_order_id_fkey" FOREIGN KEY (service_order_id) REFERENCES public.service_orders(id) ON DELETE CASCADE;

ALTER TABLE "public"."stock_movements"
  ADD CONSTRAINT "stock_movements_stock_item_id_fkey" FOREIGN KEY (stock_item_id) REFERENCES public.stock_items(id) ON DELETE CASCADE;

ALTER TABLE "public"."accounts_payable"
  ADD CONSTRAINT "accounts_payable_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."asaas_customers"
  ADD CONSTRAINT "asaas_customers_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."audit_logs"
  ADD CONSTRAINT "audit_logs_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."benefits_partners"
  ADD CONSTRAINT "benefits_partners_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."chapel_burials"
  ADD CONSTRAINT "chapel_burials_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."commissions"
  ADD CONSTRAINT "commissions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."contracts"
  ADD CONSTRAINT "contracts_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."dependents"
  ADD CONSTRAINT "dependents_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."dispatches"
  ADD CONSTRAINT "dispatches_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."emergency_dispatches"
  ADD CONSTRAINT "emergency_dispatches_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."financial_transactions"
  ADD CONSTRAINT "financial_transactions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."fiscal_invoices"
  ADD CONSTRAINT "fiscal_invoices_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."fleet_expenses"
  ADD CONSTRAINT "fleet_expenses_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."fleet_vehicles"
  ADD CONSTRAINT "fleet_vehicles_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."holders"
  ADD CONSTRAINT "holders_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."payment_carnets"
  ADD CONSTRAINT "payment_carnets_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."payments"
  ADD CONSTRAINT "payments_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."plans"
  ADD CONSTRAINT "plans_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."regulatory_reserves"
  ADD CONSTRAINT "regulatory_reserves_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."sales_commissions"
  ADD CONSTRAINT "sales_commissions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."sellers"
  ADD CONSTRAINT "sellers_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."stock_items"
  ADD CONSTRAINT "stock_items_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."stock_movements"
  ADD CONSTRAINT "stock_movements_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE "public"."tenant_whatsapp_numbers"
  ADD CONSTRAINT "tenant_whatsapp_numbers_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_roles"
  ADD CONSTRAINT "user_roles_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_roles"
  ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."dispatches"
  ADD CONSTRAINT "dispatches_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;

ALTER TABLE "public"."service_orders"
  ADD CONSTRAINT "service_orders_vehicle_id_fkey" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE SET NULL;

ALTER TABLE "public"."burial_records"
  ADD CONSTRAINT "burial_records_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public.wake_rooms(id) ON DELETE SET NULL;

ALTER TABLE "public"."webhook_events"
  ADD CONSTRAINT "webhook_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL;

ALTER TABLE "public"."whatsapp_agent_sessions"
  ADD CONSTRAINT "whatsapp_agent_sessions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;

CREATE VIEW "public"."v_service_orders_without_nfse" AS  SELECT id,
    tenant_id,
    contract_id,
    deceased_name,
    total_amount,
    burial_date,
    created_at,
    nfse_required
   FROM public.service_orders so
  WHERE ((status = 'completed'::text) AND (nfse_required = true) AND (nfse_id IS NULL) AND (NOT (EXISTS ( SELECT 1
           FROM public.fiscal_invoices fi
          WHERE ((fi.service_order_id = so.id) AND (fi.nfse_status = ANY (ARRAY['pending'::text, 'processing'::text, 'authorized'::text])))))));

CREATE INDEX idx_accounts_payable_tenant ON public.accounts_payable USING btree (tenant_id);

CREATE INDEX idx_asaas_customers_tenant ON public.asaas_customers USING btree (tenant_id);

CREATE INDEX idx_audit_logs_tenant ON public.audit_logs USING btree (tenant_id);

CREATE INDEX idx_commissions_contract_id ON public.commissions USING btree (contract_id);

CREATE INDEX idx_commissions_tenant ON public.commissions USING btree (tenant_id);

CREATE INDEX idx_contracts_status ON public.contracts USING btree (status);

CREATE INDEX idx_dispatch_audit_dispatch ON public.dispatch_audit_logs USING btree (dispatch_id);

CREATE INDEX idx_dispatch_audit_tenant ON public.dispatch_audit_logs USING btree (tenant_id);

CREATE INDEX idx_dispatches_tenant ON public.dispatches USING btree (tenant_id);

CREATE INDEX idx_emergency_dispatches_tenant ON public.emergency_dispatches USING btree (tenant_id, created_at DESC);

CREATE INDEX idx_fin_transactions_tenant_date ON public.financial_transactions USING btree (tenant_id, transaction_date);

CREATE INDEX idx_financial_transactions_service_order ON public.financial_transactions USING btree (service_order_id)
  WHERE (service_order_id IS NOT NULL);

CREATE INDEX idx_fiscal_invoices_created_at ON public.fiscal_invoices USING btree (tenant_id, created_at DESC);

CREATE INDEX idx_fiscal_invoices_nfse_number ON public.fiscal_invoices USING btree (tenant_id, nfse_number);

CREATE INDEX idx_fiscal_invoices_provider ON public.fiscal_invoices USING btree (PROVIDER, provider_invoice_id);

CREATE INDEX idx_fiscal_invoices_service_order ON public.fiscal_invoices USING btree (service_order_id);

CREATE INDEX idx_fiscal_invoices_so ON public.fiscal_invoices USING btree (service_order_id);

CREATE INDEX idx_fiscal_invoices_status ON public.fiscal_invoices USING btree (tenant_id, nfse_status);

CREATE INDEX idx_fiscal_invoices_tenant ON public.fiscal_invoices USING btree (tenant_id);

CREATE INDEX idx_holders_cpf ON public.holders USING btree (cpf);

CREATE INDEX idx_holders_tenant_id ON public.holders USING btree (tenant_id);

CREATE INDEX idx_holders_tenant_status ON public.holders USING btree (tenant_id, status);

CREATE INDEX idx_leads_converted ON public.leads USING btree (converted_at);

CREATE INDEX idx_leads_created ON public.leads USING btree (created_at DESC);

CREATE INDEX idx_leads_followup ON public.leads USING btree (next_follow_up);

CREATE INDEX idx_leads_stage ON public.leads USING btree (stage);

CREATE INDEX idx_payment_carnets_asaas_id ON public.payment_carnets USING btree (asaas_payment_id);

CREATE INDEX idx_payment_carnets_tenant ON public.payment_carnets USING btree (tenant_id);

CREATE INDEX idx_payments_due_date ON public.payments USING btree (due_date);

CREATE INDEX idx_payments_status ON public.payments USING btree (status);

CREATE INDEX idx_payments_tenant_contract ON public.payments USING btree (tenant_id, contract_id);

CREATE INDEX idx_sellers_tenant ON public.sellers USING btree (tenant_id);

CREATE INDEX idx_service_order_items_service ON public.service_order_items USING btree (service_order_id);

CREATE INDEX idx_service_orders_burial ON public.service_orders USING btree (burial_id);

CREATE INDEX idx_service_orders_contract ON public.service_orders USING btree (contract_id);

CREATE INDEX idx_service_orders_tenant ON public.service_orders USING btree (tenant_id);

CREATE INDEX idx_tenant_whatsapp_number ON public.tenant_whatsapp_numbers USING btree (whatsapp_number);

CREATE INDEX idx_user_roles_tenant_id ON public.user_roles USING btree (tenant_id);

CREATE INDEX idx_webhook_events_payment ON public.webhook_events USING btree (asaas_payment_id);

CREATE INDEX idx_webhook_events_tenant_time ON public.webhook_events USING btree (tenant_id, received_at DESC);

CREATE INDEX idx_webhook_events_unprocessed ON public.webhook_events USING btree (received_at DESC)
  WHERE (processed = false);

CREATE INDEX idx_whatsapp_sessions_tenant_phone ON public.whatsapp_agent_sessions USING btree (tenant_id, phone);

CREATE POLICY "pedrofsneto33's Org_tenant_isolation" ON "public"."pedrofsneto33's Org"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "accounts_payable_tenant_isolation" ON "public"."accounts_payable"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "asaas_customers_tenant_isolation" ON "public"."asaas_customers"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "audit_logs_tenant_isolation" ON "public"."audit_logs"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "benefit_partners_tenant_isolation" ON "public"."benefit_partners"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "benefits_partners_tenant_isolation" ON "public"."benefits_partners"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "burial_records_tenant_isolation" ON "public"."burial_records"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "chapel_bookings_tenant_isolation" ON "public"."chapel_bookings"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "chapel_burials_tenant_isolation" ON "public"."chapel_burials"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "collection_receipts_tenant_isolation" ON "public"."collection_receipts"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "collection_routes_tenant_isolation" ON "public"."collection_routes"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "collector_routes_tenant_isolation" ON "public"."collector_routes"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "commissions_tenant_isolation" ON "public"."commissions"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "contracts_tenant_isolation" ON "public"."contracts"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "convalescence_items_tenant_isolation" ON "public"."convalescence_items"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "service_role_all_convalescence_items" ON "public"."convalescence_items"
  FOR ALL
  TO "service_role"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "tenant_isolation_policy" ON "public"."convalescence_items"
  FOR ALL
  TO PUBLIC
  USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));

CREATE POLICY "convalescence_loans_tenant_isolation" ON "public"."convalescence_loans"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "service_role_all_convalescence_loans" ON "public"."convalescence_loans"
  FOR ALL
  TO "service_role"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "tenant_isolation_policy" ON "public"."convalescence_loans"
  FOR ALL
  TO PUBLIC
  USING ((tenant_id = (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid));

CREATE POLICY "dependents_tenant_isolation" ON "public"."dependents"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "dispatch_audit_logs_tenant_isolation" ON "public"."dispatch_audit_logs"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "dispatches_tenant_isolation" ON "public"."dispatches"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "duty_services_tenant_isolation" ON "public"."duty_services"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "emergency_dispatches_tenant_isolation_agent" ON "public"."emergency_dispatches"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "emergency_dispatches_tenant_isolation" ON "public"."emergency_dispatches"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "financial_transactions_tenant_isolation" ON "public"."financial_transactions"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "fiscal_invoices_tenant_isolation" ON "public"."fiscal_invoices"
  FOR ALL
  TO PUBLIC
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "fleet_expenses_tenant_isolation" ON "public"."fleet_expenses"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "fleet_vehicles_tenant_isolation" ON "public"."fleet_vehicles"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "holders_tenant_isolation" ON "public"."holders"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "inventory_tenant_isolation" ON "public"."inventory"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "inventory_items_tenant_isolation" ON "public"."inventory_items"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "payment_carnets_tenant_isolation" ON "public"."payment_carnets"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "payments_tenant_isolation" ON "public"."payments"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "plans_tenant_isolation" ON "public"."plans"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "regulatory_reserves_tenant_isolation" ON "public"."regulatory_reserves"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "sales_commissions_tenant_isolation" ON "public"."sales_commissions"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "sellers_tenant_isolation" ON "public"."sellers"
  FOR ALL
  TO PUBLIC
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "stock_items_tenant_isolation" ON "public"."stock_items"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "stock_movements_tenant_isolation" ON "public"."stock_movements"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "tenant_whatsapp_numbers_tenant_isolation" ON "public"."tenant_whatsapp_numbers"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "tenants_self_or_super" ON "public"."tenants"
  FOR ALL
  TO "authenticated"
  USING (((id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "tenants_self_read" ON "public"."tenants"
  FOR SELECT
  TO "authenticated"
  USING (((id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "thanatopraxy_records_tenant_isolation" ON "public"."thanatopraxy_records"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "user_roles_self_or_super" ON "public"."user_roles"
  FOR SELECT
  TO "authenticated"
  USING ((((user_id = auth.uid()) AND (tenant_id = public.get_user_tenant_id())) OR public.is_superadmin()));

CREATE POLICY "user_roles_self_read" ON "public"."user_roles"
  FOR SELECT
  TO "authenticated"
  USING ((auth.uid() = user_id));

CREATE POLICY "vehicles_tenant_isolation" ON "public"."vehicles"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "wake_rooms_tenant_isolation" ON "public"."wake_rooms"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "webhook_logs_tenant_isolation" ON "public"."webhook_logs"
  FOR ALL
  TO "authenticated"
  USING ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()))
  WITH CHECK ((((tenant_id)::text = (public.get_user_tenant_id())::text) OR public.is_superadmin()));

CREATE POLICY "whatsapp_agent_sessions_tenant_isolation" ON "public"."whatsapp_agent_sessions"
  FOR ALL
  TO "authenticated"
  USING (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()))
  WITH CHECK (((tenant_id = public.get_user_tenant_id()) OR public.is_superadmin()));

CREATE POLICY "tenant_logos_public_read" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'tenant-logos'::text));

COMMENT ON COLUMN "public"."fiscal_invoices"."cst" IS 'Codigo de Situacao Tributaria - Reforma Tributaria (obrigatorio a partir de 01/10/2026).';

COMMENT ON COLUMN "public"."fiscal_invoices"."nfse_status" IS 'Status: pending, processing, authorized, rejected, cancelled, error.';

COMMENT ON COLUMN "public"."tenants"."asaas_api_key" IS 'API Key da conta/subconta Asaas da funerária para recebimento direto de mensalidades';

COMMENT ON COLUMN "public"."tenants"."asaas_environment" IS 'Ambiente de transação: sandbox ou production';

COMMENT ON COLUMN "public"."tenants"."asaas_wallet_id" IS 'ID da subconta Asaas (caso opere via split/white-label centralizado)';

COMMENT ON COLUMN "public"."tenants"."fiscal_auto_emit" IS 'Se true, emite NFS-e automaticamente quando uma OS e concluida.';

COMMENT ON COLUMN "public"."tenants"."fiscal_provider" IS 'Provedor de NFS-e: nfeio, enotas, focusnfe, tecnospeed.';

COMMENT ON TABLE "public"."fiscal_invoices" IS 'Historico de tentativas de emissao de NFS-e.';

GRANT EXECUTE ON FUNCTION "public"."current_tenant_id"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."decrement_stock"(uuid, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."decrement_stock"(uuid, uuid, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."get_current_tenant_id"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."get_user_tenant_id"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."increment_stock"(uuid, uuid, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."is_superadmin"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."duty_services_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."pedrofsneto33's Org" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."accounts_payable" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."asaas_customers" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."audit_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."benefit_partners" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."benefits_partners" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."burial_records" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."chapel_bookings" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."chapel_burials" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."collection_receipts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."collection_routes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."collector_routes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."commissions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."contracts" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."convalescence_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."convalescence_loans" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."dependents" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."dispatch_audit_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."dispatches" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."duty_services" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."emergency_dispatches" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."financial_transactions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."fiscal_invoices" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."fleet_expenses" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."fleet_vehicles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."holders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventory" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventory_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."leads" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."payment_carnets" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."payments" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."plans" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."plans_orphans_backup" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."regulatory_reserves" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sales_commissions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sellers" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."service_order_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."service_orders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_items" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."stock_movements" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tenant_whatsapp_numbers" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."tenants" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."thanatopraxy_records" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_roles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."vehicles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."wake_rooms" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."webhook_events" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."webhook_logs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."whatsapp_agent_sessions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."v_service_orders_without_nfse"
  TO "anon", "authenticated", "postgres", "service_role";

